version: '3.9'
services:
  postgres:
    image: postgres:latest
    container_name: database
    restart: always
    ports:
      - 5432:5432
    env_file:
      - database.env
    volumes:
      - database:/var/lib/postgresql/data

volumes:
  database: