version: '3.9'

services:
  NestJS:
    container_name: backend
    build:
      context: .
      dockerfile: ./Dockerfile
    image: netjs
    command: npm run start:prod
    ports:
      - 3000:3000
    networks:
      - netjs
    restart: unless-stopped

networks:
  netjs: